import { Toaster } from "react-hot-toast";
import "../styles/main.css";
import "pure-react-carousel/dist/react-carousel.es.css";
import { Inter } from "next/font/google";
import AuthContextProvider from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
{/*       <AuthContextProvider> */}
        <body className={inter.className}>{children}</body>
        <Toaster />
{/*       </AuthContextProvider> */}
    </html>
  );
}
