import { QueryClientProvider } from '@tanstack/react-query';
import '../styles/main.css'
import { Inter } from 'next/font/google'
import { queryClient } from '@/api/queryClient';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Food Eshop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
